namespace HR_Management_System.Entities;

public class Employee
{
    public Guid Id { get; set; }

    // Automatically generated by the backend.
    // Example: EMP-000001
    public required string EmployeeNumber { get; set; }

    // Personal information
    public required string Name { get; set; }
    public required string Email { get; set; }
    public string? Mobile { get; set; }
    public DateTime? DateOfBirth { get; set; }
    public string? Gender { get; set; }
    public string? Nationality { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? ZipCode { get; set; }
    public string? AvatarUrl { get; set; }

    // Professional information
    public string Title { get; set; } = string.Empty;

    public EmployeeType Type { get; set; }

    public EmployeeStatus Status { get; set; }

    public DateTime JoiningDate { get; set; }

    public string? OfficeLocation { get; set; }

    // Department
    public Guid DepartmentId { get; set; }
    public Department Department { get; set; } = null!;

    // Employee links / contact IDs
    public EmployeeLinks? Links { get; set; }

    // Documents
    public ICollection<EmployeeDocument> Documents { get; set; }
        = new List<EmployeeDocument>();

    // Related records
    public ICollection<Attendance> AttendanceRecords { get; set; }
        = new List<Attendance>();

    public ICollection<Payroll> PayrollRecords { get; set; }
        = new List<Payroll>();
}